apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workerInit
spec:
  selector:
    matchLabels:
      app: workerInit
  replicas: 1
  template:
    metadata:
      labels:
        app: workerInit
    spec:
      containers:
      - name: workerInit
        image: pconnell89/workerInit #update
        resources:
          requests:
            cpu: 100m 
            memory: 100Mi 
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"    
        - name: GET_HOSTS_FROM
          value: dns